export const FETCH_FILMS_START = 'FETCH_FILMS_START'
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS'
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE'

export const FETCH_FILM_BY_ID_START = 'FETCH_FILM_BY_ID_START'
export const FETCH_FILM_BY_ID_SUCCESS = 'FETCH_FILM_BY_ID_SUCCESS'
export const FETCH_FILM_BY_ID_FAILURE = 'FETCH_FILM_BY_ID_FAILURE'

export const SEARCH_FILM = 'SEARCH_FILM'